# ---
# apiVersion: v1
# kind: PersistentVolume
# metadata:
#   name: lenshxm-site-pv
# spec:
#   storageClassName: localpath
#   capacity:
#     storage: 10Gi
#   accessModes:
#     - ReadWriteMany
#   hostPath:
#     path: /home/ajaykumarpmk/shared-disk/
# ---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: lenshxm-site-pvc
spec:
  storageClassName: localpath
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1.5Gi
  volumeName: lenshxm-site-pv
